server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create



app:
  paypalConfig:
    clientId: AYToUfLVeL7TNBwvPpkoE51hozKR4OBv3-xP6k7TLeSNdApdpnLRsTe0qr5ac8-i9xpPlsg82hCtMxXT
    clientSecret: EGJNAE_V1OYKHtw5nv638E0hN44RUKERGFD4QIn9pdWAe1uVHXJT0Zqbz1G1lRudG8ZV47NKrVgn9kGs
    mode: sandbox
    method: paypal
    intent: authorize
    quantity: 1