server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create



app:
  paypalConfig:
    clientId:
    clientSecret:
    mode: sandbox
    method: paypal
    intent: authorize
    quantity: 1